name: Sync with Organization Repo

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch: # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the Source Repo (Repo A)
        run: |
          git clone --mirror https://Sambodhan-org:${{ secrets.PAT_TOKEN }}@github.com/Sambodhan-org/0unveiled.git source-repo
          cd source-repo

      - name: Push to Target Repo (Repo B)
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://ajstars1:${PAT}@github.com/ajstars1/0unveiled.git
          git push --mirror
