name: Sync with Organization Repo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
permissions:                
  contents: write           # 'write' access to repository contents
  pull-requests: write 

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: Sambodhan-org/0unveiled
          token: ${{ secrets.PATH_TOKEN_ORG }}
          fetch-depth: 0

      - name: Set up Git configuration
        run: |
          git config --global user.name "ajstars1"
          git config --global user.email "ayushjamwal10@gmail.com"

      - name: Push to Target Repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PATH_TOKEN_PRV }}
          repository: ajstars1/0unveiled
          force: true
